spring.application.name=docpilot-backend
spring.application.port=8080
spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
github.token=${github_token_docpilot}
gemini.api.key=${gemini_api_key_docpilot}