package com.docpilot.docpilot_backend.service;

import com.docpilot.docpilot_backend.model.RepositoryAnalysis;
import com.docpilot.docpilot_backend.model.RepositorySnapshot;
import org.springframework.stereotype.Service;

@Service
public class DocGeneratorService {

    public String generateDocumentation(
            RepositorySnapshot snapshot,
            RepositoryAnalysis analysis,
            String tree,
            String aiOutput) {

        if (aiOutput != null && !aiOutput.isBlank()) {
            return aiOutput;
        }

        return """
                # %s

                ## Overview

                Documentation could not be generated by the AI service.

                ## Analysis

                - Repository files: %d
                - Source files analyzed: %d
                - Languages: %s
                - Frameworks: %s

                ## Project Structure

                ```text
                %s
                ```
                """.formatted(
                snapshot.getName(),
                snapshot.getAllPaths().size(),
                snapshot.getSourceFiles().size(),
                analysis.getLanguages(),
                analysis.getFrameworks(),
                tree
        );
    }
}
